table Reseller
	lineageTag: 8f18aec2-8698-42c2-a2d0-6e0ab97c60ed

	column ResellerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6e7e9057-9f99-4e3d-b97a-8f1971657186
		summarizeBy: none
		sourceColumn: ResellerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Business Type'
		dataType: string
		lineageTag: 22cb0578-d589-4fc7-8658-750d9783ca51
		summarizeBy: none
		sourceColumn: Business Type

		annotation SummarizationSetBy = Automatic

	column Reseller
		dataType: string
		lineageTag: b487d3bb-83eb-4ca3-a470-8efb781d68d2
		summarizeBy: none
		sourceColumn: Reseller

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 35c811f8-8abf-442d-a31e-71b02f7e1af3
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State-Province
		dataType: string
		lineageTag: 987ad92b-87ef-4c9a-87aa-7cd7c9a3036b
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State-Province

		annotation SummarizationSetBy = Automatic

	column Country-Region
		dataType: string
		lineageTag: aa6ac85c-86e5-4f58-b75a-8376c0c8ac42
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Country-Region

		annotation SummarizationSetBy = Automatic

	hierarchy Resellers
		lineageTag: a54c82a1-76ba-48de-9948-18488253b5a1

		level Reseller
			lineageTag: c409da2a-cfc5-482f-a171-80afc91352c7
			column: Reseller

		level 'Business Type'
			lineageTag: 7c25b373-faf0-4d10-a202-ee79a8923eb8
			column: 'Business Type'

	hierarchy Geography
		lineageTag: e1563909-1070-432c-b5b8-2e6b8ab5144d

		level Country-Region
			lineageTag: 2caa75c9-b1ee-4e4f-be2b-112f07f20a51
			column: Country-Region

		level State-Province
			lineageTag: 6e0b034e-4310-4f2f-8d4a-a544c023a742
			column: State-Province

		level City
			lineageTag: 732d00cb-430b-4b8f-8097-84e839c26481
			column: City

		level Reseller
			lineageTag: 81d9a1b5-da16-4b32-bf19-f4f6bc8bdb76
			column: Reseller

	partition Reseller = m
		mode: import
		source =
				let
				    Source = Sql.Databases(SQLInstance),
				    AdventureWorksDW2020 = Source{[Name=Database]}[Data],
				    dbo_DimReseller = AdventureWorksDW2020{[Schema="dbo",Item="DimReseller"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_DimReseller,{"ResellerKey", "BusinessType", "ResellerName", "DimGeography"}),
				    #"Expanded DimGeography" = Table.ExpandRecordColumn(#"Removed Other Columns", "DimGeography", {"City", "StateProvinceName", "EnglishCountryRegionName"}, {"City", "StateProvinceName", "EnglishCountryRegionName"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded DimGeography","Ware House","Warehouse",Replacer.ReplaceText,{"BusinessType"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value",{{"BusinessType", "Business Type"}, {"ResellerName", "Reseller"}, {"StateProvinceName", "State-Province"}, {"EnglishCountryRegionName", "Country-Region"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

