table SalespersonRegion
	lineageTag: 1bc088d9-fc8b-44d4-a55c-864d6465b75c

	column EmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: 8ab8ec41-c04d-4740-ac69-a93e839b2433
		summarizeBy: none
		sourceColumn: EmployeeKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: f80a41e7-424f-4921-b2e6-83ee3f6cbfe3
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition SalespersonRegion = m
		mode: import
		source =
				let
				    Source = Sql.Databases(SQLInstance),
				    AdventureWorksDW2020 = Source{[Name=Database]}[Data],
				    dbo_DimEmployeeSalesTerritory = AdventureWorksDW2020{[Schema="dbo",Item="DimEmployeeSalesTerritory"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_DimEmployeeSalesTerritory,{"DimEmployee", "DimSalesTerritory"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

