table Sales
	lineageTag: c90c54c3-ecc7-4006-acae-213e629b2b9e

	measure Profit =
			
			SUM('Sales'[Sales]) - SUM('Sales'[Cost])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e9392e16-8287-4a63-8f98-14ddbc88ec6d

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalSubtraction"
				}

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Profit Margin' =
			
			DIVIDE([Profit], SUM('Sales'[Sales]))
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 6dcf0ce0-a21f-454e-8857-7bf5e2b7b031

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'Avg Price' =
			
			AVERAGE(Sales[Unit Price])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Pricing
		lineageTag: 9ca76f2a-b132-4cb0-813c-f4e65d5f9c71

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Median Price' =
			
			MEDIAN(Sales[Unit Price])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Pricing
		lineageTag: 22c94527-a543-4638-8cf7-fb934808620e

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Min Price' =
			
			MIN(Sales[Unit Price])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Pricing
		lineageTag: 94d285a5-58ae-40fb-98dd-29b64a058507

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Max Price' =
			
			MAX(Sales[Unit Price])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Pricing
		lineageTag: 793f0df1-015b-4908-b5bd-aefbd1dfdb62

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure Orders =
			
			DISTINCTCOUNT(Sales[SalesOrderNumber])
		formatString: 0
		displayFolder: Counts
		lineageTag: 57f38fd6-cf9a-4d06-a7ee-1a306043c61b

	measure 'Order Lines' =
			
			COUNTROWS(Sales)
		formatString: 0
		displayFolder: Counts
		lineageTag: da03adc1-acfb-4d73-9aaa-b5e373c5e88f

	measure 'Sales % All Region' =
			
			DIVIDE(
				SUM(Sales[Sales]),
				CALCULATE(
					SUM(Sales[Sales]),
					REMOVEFILTERS(Region)
				)
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Ratios
		lineageTag: 008e9ca5-2758-43de-9595-76282e69f31d

	measure 'Sales % Country' =
			
			IF(
				ISINSCOPE(Region[Region]),
				DIVIDE(
					SUM(Sales[Sales]),
					CALCULATE(
						SUM(Sales[Sales]),
						REMOVEFILTERS(Region[Region])
					)
				)
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Ratios
		lineageTag: 954e603d-5c04-4a90-ad4c-8f34b04ea323

	measure 'Sales % Group' =
			
			IF(
				ISINSCOPE(Region[Region])
					|| ISINSCOPE(Region[Country]),
				DIVIDE(
					SUM(Sales[Sales]),
					CALCULATE(
						SUM(Sales[Sales]),
						REMOVEFILTERS(
							Region[Region],
							Region[Country]
						)
					)
				)
			)
		displayFolder: Ratios
		lineageTag: 565a0642-ff70-4055-95e3-f5233d204ae8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales YTD' =
			
			TOTALYTD(SUM(Sales[Sales]), 'Date'[Date], "6-30")
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Time Intelligence
		lineageTag: a9440108-f6a0-4e23-b6c9-9fa7662ff79b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Sales YoY Growth' =
			
			VAR SalesPriorYear =
				CALCULATE(
					SUM(Sales[Sales]),
					PARALLELPERIOD(
						'Date'[Date],
						-12,
						MONTH
					)
				)
			RETURN
				DIVIDE(
					(SUM(Sales[Sales]) - SalesPriorYear),
					SalesPriorYear
				)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Time Intelligence
		lineageTag: 5e215bb9-dc07-4caa-a171-431cb225e29a

	column SalesOrderNumber
		dataType: string
		isHidden
		lineageTag: f7a951a1-052d-44bb-911c-0f487977d8e6
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: f09e25ae-d1b9-4233-80a0-f947efe49834
		summarizeBy: none
		sourceColumn: OrderDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 322e241e-6244-4cd7-bb79-bf30ad967c85
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ResellerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fa69a045-873a-49b5-847a-2eda5565fab7
		summarizeBy: none
		sourceColumn: ResellerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EmployeeKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 84ab0fd3-0c83-4456-a495-f0e3817be1b3
		summarizeBy: none
		sourceColumn: EmployeeKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e2190568-d580-4d50-abaf-e366040afd52
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: #,0
		lineageTag: 1f8ac87e-c2b3-4d8f-bf03-f927b297974e
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Unit Price'
		dataType: decimal
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 914c5056-0675-4279-90b9-9b47f4096186
		summarizeBy: average
		sourceColumn: Unit Price

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Sales
		dataType: decimal
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4465de7d-4f58-462b-8ddb-6207fcce0d92
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Based in standard cost
	column Cost
		dataType: decimal
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 4891cf60-2811-4a99-9d25-63cb318cbb38
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition Sales = m
		mode: import
		source =
				let
				    Source = Sql.Databases(SQLInstance),
				    AdventureWorksDW2020 = Source{[Name=Database]}[Data],
				    dbo_FactResellerSales = AdventureWorksDW2020{[Schema="dbo",Item="FactResellerSales"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_FactResellerSales,{"SalesOrderNumber", "OrderDate", "ProductKey", "ResellerKey", "EmployeeKey", "SalesTerritoryKey", "OrderQuantity", "UnitPrice", "TotalProductCost", "SalesAmount", "DimProduct"}),
				    #"Expanded DimProduct" = Table.ExpandRecordColumn(#"Removed Other Columns", "DimProduct", {"StandardCost"}, {"StandardCost"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded DimProduct", "Cost", each if [TotalProductCost] = null then [OrderQuantity] * [StandardCost] else [TotalProductCost]),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Added Custom",{"SalesOrderNumber", "OrderDate", "ProductKey", "ResellerKey", "EmployeeKey", "SalesTerritoryKey", "OrderQuantity", "UnitPrice", "SalesAmount", "Cost"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns1",{{"OrderQuantity", "Quantity"}, {"UnitPrice", "Unit Price"}, {"SalesAmount", "Sales"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Quantity", Int64.Type}, {"Unit Price", Currency.Type}, {"Sales", Currency.Type}, {"Cost", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

